// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.flights_old */
export default interface FlightsOld {
  id: string;

  origin: string;

  destination: string;

  ac_reg: string;

  tags: string[][] | null;

  remarks: string | null;

  owner: string;

  ac_type: string | null;

  date: Date;

  captain: string;

  capacity: string;

  depart: Date;

  arrival: Date;

  day_to: number | null;

  day_ldg: number | null;

  night_to: number | null;

  night_ldg: number | null;
}

/** Represents the initializer for the table public.flights_old */
export interface FlightsOldInitializer {
  /** Default value: uuid_generate_v4() */
  id?: string;

  origin: string;

  destination: string;

  ac_reg: string;

  tags?: string[][] | null;

  remarks?: string | null;

  owner: string;

  ac_type?: string | null;

  date: Date;

  captain: string;

  capacity: string;

  depart: Date;

  arrival: Date;

  /** Default value: 0 */
  day_to?: number | null;

  /** Default value: 0 */
  day_ldg?: number | null;

  /** Default value: 0 */
  night_to?: number | null;

  /** Default value: 0 */
  night_ldg?: number | null;
}

/** Represents the mutator for the table public.flights_old */
export interface FlightsOldMutator {
  id?: string;

  origin?: string;

  destination?: string;

  ac_reg?: string;

  tags?: string[][] | null;

  remarks?: string | null;

  owner?: string;

  ac_type?: string | null;

  date?: Date;

  captain?: string;

  capacity?: string;

  depart?: Date;

  arrival?: Date;

  day_to?: number | null;

  day_ldg?: number | null;

  night_to?: number | null;

  night_ldg?: number | null;
}
