// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.flights */
export default interface Flights {
  id: string;

  owner: string;

  date: Date;

  ac_type: string;

  ac_reg: string;

  captain: string;

  op_capacity: string;

  origin: string;

  destination: string;

  departure: string;

  arrival: string;

  day_se_p1: unknown | null;

  day_se_p2: unknown | null;

  day_me_p1: unknown | null;

  day_me_p2: unknown | null;

  night_se_p1: unknown | null;

  night_se_p2: unknown | null;

  night_me_p1: unknown | null;

  night_me_p2: unknown | null;

  instrument: unknown | null;

  sim: unknown | null;

  day_to: number | null;

  day_ldg: number | null;

  night_to: number | null;

  night_ldg: number | null;

  remarks: string | null;

  tags: string[][] | null;
}

/** Represents the initializer for the table public.flights */
export interface FlightsInitializer {
  /** Default value: uuid_generate_v4() */
  id?: string;

  owner: string;

  date: Date;

  ac_type: string;

  ac_reg: string;

  captain: string;

  op_capacity: string;

  origin: string;

  destination: string;

  departure: string;

  arrival: string;

  day_se_p1?: unknown | null;

  day_se_p2?: unknown | null;

  day_me_p1?: unknown | null;

  day_me_p2?: unknown | null;

  night_se_p1?: unknown | null;

  night_se_p2?: unknown | null;

  night_me_p1?: unknown | null;

  night_me_p2?: unknown | null;

  instrument?: unknown | null;

  sim?: unknown | null;

  /** Default value: 0 */
  day_to?: number | null;

  /** Default value: 0 */
  day_ldg?: number | null;

  /** Default value: 0 */
  night_to?: number | null;

  /** Default value: 0 */
  night_ldg?: number | null;

  remarks?: string | null;

  tags?: string[][] | null;
}

/** Represents the mutator for the table public.flights */
export interface FlightsMutator {
  id?: string;

  owner?: string;

  date?: Date;

  ac_type?: string;

  ac_reg?: string;

  captain?: string;

  op_capacity?: string;

  origin?: string;

  destination?: string;

  departure?: string;

  arrival?: string;

  day_se_p1?: unknown | null;

  day_se_p2?: unknown | null;

  day_me_p1?: unknown | null;

  day_me_p2?: unknown | null;

  night_se_p1?: unknown | null;

  night_se_p2?: unknown | null;

  night_me_p1?: unknown | null;

  night_me_p2?: unknown | null;

  instrument?: unknown | null;

  sim?: unknown | null;

  day_to?: number | null;

  day_ldg?: number | null;

  night_to?: number | null;

  night_ldg?: number | null;

  remarks?: string | null;

  tags?: string[][] | null;
}
